#!/bin/sh
#
# Script to start/stop/restart containers on Eris Linux system.
#
# Christophe BLAESS 2024.
# (c) 2024-2026 Logilin.


CONTAINERS_FILE="/etc/eris-linux/containers"
SLOTS_DIR="/data/containers"
CONTAINERS_STORAGE="/data/container-storage"

MIN_SLOT_NUMBER=1
MAX_SLOT_NUMBER=4

X11_OPT="-e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix"

# The following lines produces a light container with ABI-dependency on Yocto-produced Qt libraries.
#GCC_OPT="-v /lib:/gcclib:ro"
#LIB_OPT="-e LD_LIBRARY_PATH=/qt-usr-lib:/gcclib"
#QT6_OPT="-v /usr/lib/:/qt-usr-lib:ro -e QT_QPA_PLATFORM_PLUGIN_PATH=/qt-usr-lib/plugins/platforms"
#FONT_OPT="-v /etc/fonts:/etc/fonts:ro -v /usr/share/fonts:/usr/share/fonts:ro"


start_container()
{
	local slot="${1}"
	local slot_name="slot-${slot}"
	local container_name="cnt-${slot}"
	local slot_dir="${SLOTS_DIR}/${slot_name}"
	local error_file="/run/container-error-${slot}"
	local tmp_error_file="/run/container-error-${slot}.$$"
	local id=""
	local label=""
	local version=""
	local filename=""
	local b64=""
	local graphical=""
	local redirections=""
	local privileged=""
	local rest=""
	local count=${MIN_SLOT_NUMBER}
	local output=""
	local run_code=0

	if [ "${slot}" = "" ] || [ ${slot} -lt ${MIN_SLOT_NUMBER} ] || [ ${slot} -gt ${MAX_SLOT_NUMBER} ]; then return; fi

	while IFS=! read id label version filename b64 graphical redirections privileged
	do
		if [ "${count}" = "${slot}" ]; then break; fi
		count=$((count + 1))
	done < "${CONTAINERS_FILE}"


	if [ "${id}" = "" ] || [ "${id}" = "-1" ]; then
		rm -f "${error_file}"
	return; fi

	if [ -f "${slot_dir}/slot.tar" ]
	then
		docker image rm "${slot_name}" >/dev/null 2>&1

		output=$(docker import - ${slot_name} < "${slot_dir}/slot.tar" 2>&1)
		run_code=$?

		if [ "${run_code}" -ne 0 ]
		then
			printf "%d\n" 5 > "${tmp_error_file}"
			printf "%s" "${output}" >> "${tmp_error_file}"
			mv  "${tmp_error_file}"  "${error_file}"
			return
		fi

		local cmd=""
		if [ -f "${slot_dir}/slot.cmd" ]
		then
			cmd=$(cat "${slot_dir}/slot.cmd")
		fi

		local docker_opts="--add-host=host.docker.internal:host-gateway"
		docker_opts="${docker_opts} --mount type=bind,source=${CONTAINERS_STORAGE},target=/data"

		if [ "${graphical:0:1}" = "Y" ] || [ "${graphical:0:1}" = "y" ]
		then
			docker_opts="${docker_opts} ${X11_OPT} ${QT6_OPT} ${GCC_OPT} ${LIB_OPT} ${FONT_OPT}"
		fi

		for redirection in ${redirections}
		do
			local ext_port=""
			local int_port=""
			local option=""
			local protocol=""

			option="${redirection}"
			# Expected: <external port>:<internal port>/<protocol>
			ext_port="${option%%:*}"
			option="${option#*:}"
			if [ "${ext_port}" = "${option}" ] || [ "${option}" = "" ]
			then
				int_port="${ext_port}"
				protocol="tcp"
			else
				int_port="${option%/*}"
				protocol="${option#*/}"
				if [ "${int_port}" = "${protocol}" ] || [ "${protocol}" = "" ]
				then
					protocol="tcp"
				fi
			fi
			docker_opts="${docker_opts} -p ${ext_port}:${int_port}/${protocol}"
		done

		if [ "${privileged:0:1}" = "Y" ] || [ "${privileged:0:1}" = "y" ]
		then
			docker_opts="${docker_opts} --privileged"
		fi

		docker rm -f "${slot_name}" >/dev/null 2>&1
		output=$(docker run -d --init ${docker_opts} --name "${container_name}" "${slot_name}" ${cmd} 2>&1)
		run_code=$?

		if [ ${run_code} -eq 0 ]; then
			rm -f "${error_file}"
		else
			if   [ ${run_code} -eq 126 ]; then
				# Invalid command.
				printf "%d\n" 7 > "${tmp_error_file}"
			elif [ ${run_code} -eq 127 ]; then
				# Missing app.
				printf "%d\n" 8 > "${tmp_error_file}"
			else
				# Running error.
				printf "%d\n" 6 > "${tmp_error_file}"
			fi
			echo "${output}" >> "${tmp_error_file}"
			mv  "${tmp_error_file}"  "${error_file}"
		fi
	fi
}



start_all_containers()
{
	local slot=${MIN_SLOT_NUMBER}

	while IFS=! read id rest
	do
		if [ ${id} -ge 0 ]
		then
			start_container ${slot} ${id}
		fi

		slot=$(( ${slot} + 1 ))

	done < "${CONTAINERS_FILE}"
}



stop_container()
{
	local name="slot-${1}"

	docker stop -t 5 "${name}" >/dev/null 2>&1
}



stop_all_containers()
{
	local i

	for i in $(seq ${MIN_SLOT_NUMBER} ${MAX_SLOT_NUMBER})
	do
		stop_container "$i"
	done
}



display_help()
{
		echo "Usage: $0 {start|stop|restart|start-slot <n>|stop-slot <n>|restart-slot <n>}"
}



touch "${CONTAINERS_FILE}"
for s in $(seq ${MIN_SLOT_NUMBER} ${MAX_SLOT_NUMBER})
do
	mkdir -p "${SLOTS_DIR}/slot-${s}"
done
mkdir -p "${CONTAINERS_STORAGE}"


case "$1" in
	start)
		echo -n "Starting Eris containers... "
		start_all_containers
		echo "done."
		;;

	start-slot)
		if [ $# -ge 2 ] && [ $2 -ge ${MIN_SLOT_NUMBER} ] && [ $2 -le ${MAX_SLOT_NUMBER} ]
		then
			echo -n "Starting Eris container $2... "
        	        start_container $2
	                echo "done."
		else
			display_help
			exit 1
		fi
                ;;

	stop)
		echo -n "Stopping Eris containers... "
		stop_all_containers
		echo "done."
		;;

	stop-slot)
		if [ $# -ge 2 ] && [ $2 -ge ${MIN_SLOT_NUMBER} ] && [ $2 -le ${MAX_SLOT_NUMBER} ]
		then
			echo -n "Stopping Eris container $2... "
	                stop_container $2
        	        echo "done."
		else
			display_help
			exit 1
		fi
                ;;

	force-reload|restart)
		echo -n "Stopping and restarting Eris containers..."
		stop_all_containers
		start_all_containers
		echo "done."
		;;

	restart-slot)
		if [ $# -ge 2 ] && [ $2 -ge ${MIN_SLOT_NUMBER} ] && [ $2 -le ${MAX_SLOT_NUMBER} ]
		then
			echo "Restarting Eris container $2... "
	                stop_container $2
        	        start_container $2
			echo "Done."
		else
			display_help
			exit 1
		fi
                ;;

	*)
		display_help
		exit 1
		;;
esac

exit 0
