#!/bin/sh

source /usr/share/eris-linux/partitions


current_part=$(sed -e "s%^.*root=${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}\([0-9]\+\).*$%\1%" /proc/cmdline)

# At first boot we prepare the partitionning scheme.
#
if [ ! -b "${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_SYSTEM_B}" ] || [ ! -b "${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_DATA}" ]
then
	echo "Preparing system partitions..."

	REDIRECT=">/dev/null 2>&1"
	REDIRECT=""

	# Remove: System-B, Data.
	fdisk ${ERIS_STORAGE_DEVICE} >/dev/null 2>&1 <<- EOF1
		d
		${ERIS_PARTITION_SYSTEM_B}
		w
	EOF1

	fdisk ${ERIS_STORAGE_DEVICE} >/dev/null 2>&1 <<- EOF2
		d
		${ERIS_PARTITION_DATA}
		w
	EOF2

	echo "Create System-B partition"
	system_b_start=$(fdisk -l ${ERIS_STORAGE_DEVICE} | awk '($1 == "'${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_SYSTEM_A}'") { printf $3 + 1}' )
	rootfs_size=$(fdisk -l ${ERIS_STORAGE_DEVICE} | awk '($1 == "'${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_SYSTEM_A}'") { printf $4 + 1024}' )

	fdisk ${ERIS_STORAGE_DEVICE} ${REDIRECT} <<- EOF3
		n
		p
		3
		${system_b_start}
		+${rootfs_size}
		w
	EOF3

	echo "Create Data partition"
	# ... and tag the partition with arbitrary type "25"
	data_start=$(fdisk -l ${ERIS_STORAGE_DEVICE} | awk '($1 == "'${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_SYSTEM_B}'") { printf $3 + 1}' )
	fdisk ${ERIS_STORAGE_DEVICE} ${REDIRECT} <<- EOF4
		n
		p
		${data_start}

		t
		${ERIS_PARTITION_DATA}
		25
		w
	EOF4

	echo "Wipe out Data partition"
	dd if=/dev/zero of=${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_DATA} bs=4M count=4

	echo "Reboot"
	mount ${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_BOOT} /boot
	/usr/sbin/force-boot-on-partition A
	sync
	/usr/sbin/fast-reboot
	while true; do : ; done
fi

data_part=$(fdisk -l /dev/mmcblk0 | awk '($1 == "'${data_part}'") { print $6 }')

# At second boot we initialize the crypted data partition
#
if [ "${part_type}" = "25" ]
then
	fdisk ${ERIS_STORAGE_DEVICE} 2>/dev/null >&2 <<- EOF8
		t
		${ERIS_PARTITION_DATA}
		83
		w
	EOF8

	source /etc/eris-linux/encryption
	if [ "${ERIS_DATA_CRYPT}" = "y" ]
	then
		mount none /run -t tmpfs
		mount none /var -t tmpfs
		mkdir /var/tmp
		if [ -x /usr/sbin/get-dmk ]
		then
			/usr/sbin/get-dmk > /tmp/key.bin
		else
			cat /proc/cpuinfo | sed -ne 's/^Serial.*: //p' > /tmp/key.bin
		fi

		echo "Preparing data partition for encryption."
		dd if=/dev/zero of=${data_part} bs=1M count=4 >/dev/null 2>&1
		/usr/sbin/cryptsetup luksFormat  \
			--batch-mode             \
			--type luks2             \
			--cipher aes-xts-plain64 \
			--key-size 512           \
			--hash sha256            \
			--key-file /tmp/key.bin  \
			${data_part}
		rm -f /tmp/key.bin
		umount /var
		umount /run
	fi
fi
