#!/bin/sh

source /usr/share/eris-linux/partitions

# At first boot we prepare the partitionning scheme.
#
if [ ! -b "${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_EXTENDED}" ]
then
	extended_start=$(fdisk -l ${ERIS_STORAGE_DEVICE} | awk '($1 == "'${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_SYSTEM_A}'") { printf $3 + 1}' )
	# the rootfs size is slightly increased to avoid _no space left_ message
	rootfs_size=$(fdisk -l ${ERIS_STORAGE_DEVICE} | awk '($1 == "'${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_SYSTEM_R}'") { printf $4 + 1024}' )
	data_size="2G"

	echo "Preparing system partitions..."

	# Remove: Data, SystemB, Extended.
	fdisk ${ERIS_STORAGE_DEVICE} 2>/dev/null >&2 <<- EOF1
		d
		${ERIS_PARTITION_DATA}
		w
	EOF1

	fdisk ${ERIS_STORAGE_DEVICE} 2>/dev/null >&2 <<- EOF2
		d
		${ERIS_PARTITION_SYSTEM_B}
		w
	EOF2

	fdisk ${ERIS_STORAGE_DEVICE} 2>/dev/null >&2 <<- EOF4
		d
		${ERIS_PARTITION_EXTENDED}
		w
	EOF4

	# Create Extended
	fdisk ${ERIS_STORAGE_DEVICE} 2>/dev/null >&2 <<- EOF5
		n
		e
		${extended_start}

		w
	EOF5

	# Create System B
	fdisk ${ERIS_STORAGE_DEVICE} 2>/dev/null >&2 <<- EOF6
		n
		l

		+${rootfs_size}
		w
	EOF6

	# Create Data and tag with arbitrary type "25"
	fdisk ${ERIS_STORAGE_DEVICE} 2>/dev/null >&2 <<- EOF7
		n
		l

		+${data_size}
		t
		${ERIS_PARTITION_DATA}
		25
		w
	EOF7
	mount ${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_BOOT} /boot
	/usr/sbin/force-boot-on-partition A
	sync
	/usr/sbin/fast-reboot
	while true; do : ; done
fi

data_part="${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_DATA}"
part_type=$(fdisk -l /dev/mmcblk0 | awk '($1 == "'${data_part}'") { print $6 }')

# At second boot we initialize the crypted data partition
#
if [ "${part_type}" = "25" ]
then
	fdisk ${ERIS_STORAGE_DEVICE} 2>/dev/null >&2 <<- EOF8
		t
		${ERIS_PARTITION_DATA}
		83
		w
	EOF8

	mount none /run -t tmpfs
	mount none /var -t tmpfs
	mkdir /var/tmp
	serial_number=$(cat /proc/cpuinfo | sed -ne 's/^Serial.*: //p')
	printf "${serial_number}" | sha256sum | sed -e 's/ .*//' > /tmp/key.bin

	echo "Encrypting data partition."
	dd if=/dev/zero of=${data_part} bs=1M count=4 >/dev/null 2>&1
	/usr/sbin/cryptsetup luksFormat  \
		--batch-mode             \
		--type luks2             \
		--cipher aes-xts-plain64 \
		--key-size 512           \
		--hash sha256            \
		--key-file /tmp/key.bin  \
		${data_part}
	echo "Encrypted"
	rm -f /tmp/key.bin
	umount /var
	umount /run
fi
