#!/bin/sh
#
# SPDX-License-Identifier: MIT
#
# Script to mount a read-write data partition, to check the filesystem in
# case of mount failure, and to reformate the partition if the check failed.
#

source /usr/share/eris-linux/partitions
if [ -f /boot/data-encryption ]
then
	source /boot/data-encryption
else
	ERIS_DATA_CRYPT=n
fi

PARTITION="${ERIS_STORAGE_DEVICE}${ERIS_PARTITION_SEPARATOR}${ERIS_PARTITION_DATA}"
MOUNTDEVICE="${PARTITION}"
MOUNTPOINT=/data
FILESYSTEM=f2fs

printf "Preparing data partition..." >&2

if [ "${ERIS_DATA_CRYPT}" = "y" ]
then
	DM_NAME="Data"
	DM_BLOCK="/dev/mapper/${DM_NAME}"

	if [ -x /usr/sbin/get-dmk ]
	then
		/usr/sbin/get-dmk > /tmp/key.bin
	else
		cat /proc/cpuinfo | sed -ne 's/^Serial.*: //p' > /tmp/key.bin
	fi

	if ! cryptsetup luksOpen --key-file /tmp/key.bin ${PARTITION} ${DM_NAME}
	then
		rm -f /tmp/key.bin
		exit 1
	fi
	rm -f /tmp/key.bin

	MOUNTDEVICE="${DM_BLOCK}"
fi

if mount ${MOUNTDEVICE} ${MOUNTPOINT} -t ${FILESYSTEM} >/dev/null 2>&1
then
	mkdir -p "${MOUNTPOINT}/containers"
	exit 0
fi

if fsck.${FILESYSTEM} -p ${MOUNTDEVICE} >/dev/null 2>&1
then
	if mount ${MOUNTDEVICE} ${MOUNTPOINT} -t ${FILESYSTEM} >/dev/null 2>&1
	then
		mkdir -p "${MOUNTPOINT}/containers"
		exit 0
	fi
fi

if [ "${FILESYSTEM}" = "vfat" ]
then
	mkfs.vfat -c -n DATA ${MOUNTDEVICE} >/dev/null 2>&1
elif [ "${FILESYSTEM}" = "f2fs" ]
then
	mkfs.f2fs -f -l DATA ${MOUNTDEVICE} >/dev/null 2>&1
else
	mkfs.${FILESYSTEM} -c -L DATA -q ${MOUNTDEVICE} >/dev/null 2>&1
fi


if mount ${MOUNTDEVICE} ${MOUNTPOINT} -t ${FILESYSTEM} >/dev/null 2>&1
then
	mkdir -p "${MOUNTPOINT}/containers"
	exit 0
fi

exit 1
