#!/bin/sh
#
# SPDX-License-Identifier: MIT
#
# Script to mount an overlayfs over `/etc/`.
# The `/` partition is supposed to be mounted read-only.
# The `/data` partition is mounted in read-write mode (see script 020).
#
WORKDIR=/data/overlayfs/etc/workdir
UPPERDIR=/data/overlayfs/etc/upperdir

if [ ! -d "${WORKDIR}" ] || [ ! -d "${UPPERDIR}" ]
then
	mkdir -p "${WORKDIR}"  "${UPPERDIR}"
fi

# Take a backup of original /etc/network. See below.
if [ -f /etc/eris-linux/network ]; then cp /etc/eris-linux/network /tmp/; fi

mount none /etc -t overlay -o lowerdir=/etc,workdir="${WORKDIR}",upperdir="${UPPERDIR}"

# Force /etc/eris-linux/network to be on the overlay.
# This is needed on the first boot to save the network parameters written by `prepare-image`.
#
touch /etc/eris-linux/network

# Restore original network file if it is corrupted.
# This is a dirty hack, but this file is very important, it's the only link with the device manager.
if [ ! -s /etc/eris-linux/network ]; then if [ -e /tmp/network ]; then cp /tmp/network /etc/eris-linux/network; fi; fi
rm -f /tmp/network

# Copy `organization-id` written by `prepare-image` on the overlay to protect it from system updates.
if [ -f /usr/share/eris-linux/organization-id ]; then cp /usr/share/eris-linux/organization-id /etc/eris-linux; fi
