#!/bin/sh
#
# SPDX-License-Identifier: MIT
#
# Script to mount an overlayfs over `/etc/`.
# The `/` partition is supposed to be mounted read-only.
# The `/data` partition is mounted in read-write mode (see script 020).
#
WORKDIR=/data/overlayfs/etc/workdir
UPPERDIR=/data/overlayfs/etc/upperdir

if [ ! -d "${WORKDIR}" ] || [ ! -d "${UPPERDIR}" ]
then
	mkdir -p "${WORKDIR}"  "${UPPERDIR}"
fi

mount none /etc -t overlay -o lowerdir=/etc,workdir="${WORKDIR}",upperdir="${UPPERDIR}"

# Force all files configured during image preparation to be on the overlay to survive future updates.
#
touch /etc/eris-linux/network
touch /etc/eris-linux/organization-id
touch /etc/wpa_supplicant.conf
